services:
  - type: web
    name: quant-rag-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    plan: free

  - type: web
    name: quant-rag
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: streamlit run app/ui/streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: API_URL
        value: https://quant-rag-api.onrender.com
    plan: free
